# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  
  functions = "./server"


# A basic redirect rule
# [[redirects]]
#   from = "/*"
#   to = "/blog/:splat"



# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

